<?php

namespace App\Domains\Production\Controllers;

use App\Domains\Inventory\Models\Product;
use App\Domains\Inventory\Models\Warehouse;
use App\Domains\Production\Models\ProductionBatch;
use App\Domains\Production\Models\ProductionOrder;
use App\Domains\Production\Models\ProductionSerialNumber;
use App\Domains\Production\Services\CodeService;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Gate;

/**
 * LabelController — Printable HTML labels for production entities.
 *
 * Correction #12: Product/SKU labels and Inventory Batch (lot) labels are separate.
 * printProductSku() generates a label identifying the product/SKU itself.
 * printBatch() generates a label for a specific production lot (batch number, expiry, qty).
 *
 * Correction #17: Labels are printable HTML only — no PDF package required.
 *
 * All labels use business-identifier barcodes (PO:, LOT:, SN:, PRD:) generated by CodeService.
 */
class LabelController extends Controller
{
    public function __construct(
        private readonly CodeService $codeService
    ) {}

    /**
     * Print a label for a Production Order.
     * Barcode: PO:{order_number}
     */
    public function printOrder(string|int $id)
    {
        $tenantId = require_tenant_id();
        $order = ProductionOrder::withoutGlobalScopes()
            ->with('product')
            ->where('tenant_id', $tenantId)
            ->where(function ($q) use ($id) {
                if (is_numeric($id)) {
                    $q->where('id', (int) $id);
                }
                $q->orWhere('order_number', $id)->orWhere('barcode', $id);
            })
            ->firstOrFail();

        Gate::authorize('view', $order);

        $barcode = 'PO:' . $order->order_number;

        return view('modules.production.labels.order', compact('order', 'barcode'));
    }

    /**
     * Print a label for a Production Batch (lot).
     * Barcode: LOT:{batch_number}
     *
     * Note: This is a production-lot label, not a product/SKU label.
     * Use printProductSku() for product identification labels.
     */
    public function printBatch(string|int $id)
    {
        Gate::authorize('viewAny', ProductionOrder::class);

        $tenantId = require_tenant_id();
        $batch = ProductionBatch::withoutGlobalScopes()
            ->with('product')
            ->where('tenant_id', $tenantId)
            ->where(function ($q) use ($id) {
                if (is_numeric($id)) {
                    $q->where('id', (int) $id);
                }
                $q->orWhere('batch_number', $id)->orWhere('barcode', $id);
            })
            ->firstOrFail();

        $barcode = 'LOT:' . $batch->batch_number;

        return view('modules.production.labels.batch', compact('batch', 'barcode'));
    }

    /**
     * Print a label for a Production Serial Number.
     * Barcode: SN:{serial_number}
     */
    public function printSerial(string|int $id)
    {
        Gate::authorize('viewAny', ProductionOrder::class);

        $tenantId = require_tenant_id();
        $serial = ProductionSerialNumber::withoutGlobalScopes()
            ->with('product')
            ->where('tenant_id', $tenantId)
            ->where(function ($q) use ($id) {
                if (is_numeric($id)) {
                    $q->where('id', (int) $id);
                }
                $q->orWhere('serial_number', $id)->orWhere('barcode', $id);
            })
            ->firstOrFail();

        $barcode = 'SN:' . $serial->serial_number;

        return view('modules.production.labels.serial', compact('serial', 'barcode'));
    }

    /**
     * Print a product/SKU identification label.
     * Barcode: PRD:{sku}
     *
     * Correction #12: This labels the PRODUCT/SKU, not a specific inventory lot.
     * Use printBatch() for lot-level labels.
     */
    public function printProductSku(string|int $id)
    {
        $tenantId = require_tenant_id();
        $product = Product::withoutGlobalScopes()
            ->where('tenant_id', $tenantId)
            ->where(function ($q) use ($id) {
                if (is_numeric($id)) {
                    $q->where('id', (int) $id);
                }
                $q->orWhere('sku', $id);
            })
            ->firstOrFail();

        Gate::authorize('view', $product);

        $barcode = 'PRD:' . $product->sku;

        return view('modules.production.labels.product-sku', compact('product', 'barcode'));
    }
}
