<?php

namespace App\Domains\Production\Controllers;

use App\Domains\Inventory\Models\Product;
use App\Domains\Inventory\Models\Warehouse;
use App\Domains\Production\Models\ProductionBatch;
use App\Domains\Production\Models\ProductionOrder;
use App\Domains\Production\Models\ProductionSerialNumber;
use App\Domains\Production\Services\CodeService;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Gate;

/**
 * LabelController — Printable HTML labels for production entities.
 *
 * Correction #12: Product/SKU labels and Inventory Batch (lot) labels are separate.
 * printProductSku() generates a label identifying the product/SKU itself.
 * printBatch() generates a label for a specific production lot (batch number, expiry, qty).
 *
 * Correction #17: Labels are printable HTML only — no PDF package required.
 *
 * All labels use business-identifier barcodes (PO:, LOT:, SN:, PRD:) generated by CodeService.
 */
class LabelController extends Controller
{
    public function __construct(
        private readonly CodeService $codeService
    ) {}

    /**
     * Print a label for a Production Order.
     * Barcode: PO:{order_number}
     */
    public function printOrder(int $id)
    {
        Gate::authorize('view', ProductionOrder::findOrFail($id));

        $order    = ProductionOrder::with('product')->findOrFail($id);
        $barcode  = 'PO:' . $order->order_number;

        return view('modules.production.labels.order', compact('order', 'barcode'));
    }

    /**
     * Print a label for a Production Batch (lot).
     * Barcode: LOT:{batch_number}
     *
     * Note: This is a production-lot label, not a product/SKU label.
     * Use printProductSku() for product identification labels.
     */
    public function printBatch(int $id)
    {
        Gate::authorize('view', ProductionOrder::class);

        $tenantId = require_tenant_id();
        $batch    = ProductionBatch::with('product')
            ->where('tenant_id', $tenantId)
            ->findOrFail($id);

        $barcode = 'LOT:' . $batch->batch_number;

        return view('modules.production.labels.batch', compact('batch', 'barcode'));
    }

    /**
     * Print a label for a Production Serial Number.
     * Barcode: SN:{serial_number}
     */
    public function printSerial(int $id)
    {
        Gate::authorize('view', ProductionOrder::class);

        $tenantId = require_tenant_id();
        $serial   = ProductionSerialNumber::with('product')
            ->where('tenant_id', $tenantId)
            ->findOrFail($id);

        $barcode = 'SN:' . $serial->serial_number;

        return view('modules.production.labels.serial', compact('serial', 'barcode'));
    }

    /**
     * Print a product/SKU identification label.
     * Barcode: PRD:{sku}
     *
     * Correction #12: This labels the PRODUCT/SKU, not a specific inventory lot.
     * Use printBatch() for lot-level labels.
     */
    public function printProductSku(int $id)
    {
        Gate::authorize('view', Product::class);

        $tenantId = require_tenant_id();
        $product  = Product::where('tenant_id', $tenantId)->findOrFail($id);
        $barcode  = 'PRD:' . $product->sku;

        return view('modules.production.labels.product-sku', compact('product', 'barcode'));
    }
}
