<?php

namespace App\Domains\Platform\Services;

class NotificationEventCatalog
{
    /**
     * Get all supported ERP Events grouped by module.
     */
    public static function getEvents(): array
    {
        return [
            'crm' => [
                'label' => 'CRM & Lead Management',
                'events' => [
                    'crm.lead.created' => [
                        'label' => 'New Lead Created',
                        'description' => 'Triggered when a new lead is captured or imported.',
                        'icon' => 'feather-user-plus',
                        'default_roles' => ['Sales Manager', 'CRM Executive'],
                        'default_title' => 'New Lead Created: {{company_name}}',
                        'default_body' => 'Lead {{company_name}} (Contact: {{contact_person}}) created with source {{source}}.',
                        'action_route' => 'crm.leads.index',
                        'variables' => ['company_name', 'contact_person', 'source', 'expected_amount', 'created_by'],
                    ],
                    'crm.deal.won' => [
                        'label' => 'Deal Won',
                        'description' => 'Triggered when a sales deal is successfully marked as Won.',
                        'icon' => 'feather-award',
                        'default_roles' => ['Sales Manager', 'Sales Head', 'Accountant'],
                        'default_title' => '🎉 Deal Won: {{deal_title}}',
                        'default_body' => 'Deal {{deal_title}} for {{customer_name}} amounting to {{amount}} has been marked as WON.',
                        'action_route' => 'crm.deals.index',
                        'variables' => ['deal_title', 'customer_name', 'amount', 'won_by'],
                    ],
                    'crm.quotation.created' => [
                        'label' => 'CRM Quotation Created',
                        'description' => 'Triggered when a new quotation is issued to a lead or customer.',
                        'icon' => 'feather-file',
                        'default_roles' => ['Sales Manager'],
                        'default_title' => 'Quotation Created: {{quotation_no}}',
                        'default_body' => 'Quotation {{quotation_no}} for {{customer_name}} amounting to {{amount}} has been created.',
                        'action_route' => 'crm.quotations.index',
                        'variables' => ['quotation_no', 'customer_name', 'amount', 'created_by'],
                    ],
                ],
            ],
            'sales' => [
                'label' => 'Sales & Revenue',
                'events' => [
                    'sales.order.created' => [
                        'label' => 'Sales Order Created',
                        'description' => 'Triggered when a draft/new sales order is created.',
                        'icon' => 'feather-shopping-bag',
                        'default_roles' => ['Sales Manager', 'Store Keeper'],
                        'default_title' => 'New Sales Order Created: {{doc_no}}',
                        'default_body' => 'Sales Order {{doc_no}} for {{customer_name}} amounting to {{amount}} has been created.',
                        'action_route' => 'sales.orders.index',
                        'variables' => ['doc_no', 'customer_name', 'amount', 'created_by', 'date'],
                    ],
                    'sales.order.confirmed' => [
                        'label' => 'Sales Order Confirmed',
                        'description' => 'Triggered when a sales order is confirmed for fulfillment.',
                        'icon' => 'feather-check-circle',
                        'default_roles' => ['Store Manager', 'Warehouse Supervisor', 'Accountant'],
                        'default_title' => 'Sales Order Confirmed: {{doc_no}}',
                        'default_body' => 'Sales Order {{doc_no}} for {{customer_name}} ({{amount}}) is confirmed. Ready for material check & dispatch.',
                        'action_route' => 'sales.orders.index',
                        'variables' => ['doc_no', 'customer_name', 'amount', 'confirmed_by', 'date'],
                    ],
                    'sales.invoice.created' => [
                        'label' => 'Sales Invoice Generated',
                        'description' => 'Triggered when a sales invoice is posted/generated.',
                        'icon' => 'feather-file-text',
                        'default_roles' => ['Accountant', 'Sales Head'],
                        'default_title' => 'Invoice Generated: {{doc_no}}',
                        'default_body' => 'Invoice {{doc_no}} for {{customer_name}} with amount {{amount}} has been generated. Due: {{due_date}}.',
                        'action_route' => 'sales.invoices.index',
                        'variables' => ['doc_no', 'customer_name', 'amount', 'due_date', 'created_by'],
                    ],
                    'sales.payment.received' => [
                        'label' => 'Customer Payment Received',
                        'description' => 'Triggered when a customer payment receipt is recorded.',
                        'icon' => 'feather-dollar-sign',
                        'default_roles' => ['Accountant', 'Sales Manager'],
                        'default_title' => 'Payment Received: {{amount}} from {{customer_name}}',
                        'default_body' => 'Payment receipt {{doc_no}} of {{amount}} received from {{customer_name}} via {{payment_method}}.',
                        'action_route' => 'sales.payments.index',
                        'variables' => ['doc_no', 'customer_name', 'amount', 'payment_method', 'date'],
                    ],
                    'sales.dispatch.shipped' => [
                        'label' => 'Dispatch Order Shipped',
                        'description' => 'Triggered when a dispatch order leaves warehouse.',
                        'icon' => 'feather-truck',
                        'default_roles' => ['Sales Manager', 'Customer Support'],
                        'default_title' => 'Order Dispatched: {{doc_no}}',
                        'default_body' => 'Dispatch {{doc_no}} for {{customer_name}} has been shipped via {{transporter}} (LR: {{tracking_no}}).',
                        'action_route' => 'inventory.dispatches.index',
                        'variables' => ['doc_no', 'customer_name', 'transporter', 'tracking_no', 'date'],
                    ],
                    'sales.return.created' => [
                        'label' => 'Sales Return Requested',
                        'description' => 'Triggered when a customer sales return is submitted.',
                        'icon' => 'feather-rotate-ccw',
                        'default_roles' => ['Store Manager', 'Quality Inspector', 'Accountant'],
                        'default_title' => 'Sales Return Logged: {{doc_no}}',
                        'default_body' => 'Sales Return {{doc_no}} from {{customer_name}} for reason: {{reason}} is awaiting inspection.',
                        'action_route' => 'sales.returns.index',
                        'variables' => ['doc_no', 'customer_name', 'reason', 'date'],
                    ],
                ],
            ],
            'inventory' => [
                'label' => 'Store & Inventory',
                'events' => [
                    'inventory.stock.low' => [
                        'label' => 'Low Stock Alert (Below Reorder Point)',
                        'description' => 'Triggered when an item stock drops below its reorder point.',
                        'icon' => 'feather-alert-triangle',
                        'default_roles' => ['Store Manager', 'Purchase Manager'],
                        'default_title' => '⚠️ Low Stock Alert: {{item_name}}',
                        'default_body' => 'Item {{item_name}} (SKU: {{sku}}) is below reorder level. Current Stock: {{current_stock}} {{uom}}, Reorder Level: {{reorder_point}} {{uom}}.',
                        'action_route' => 'inventory.products.index',
                        'variables' => ['item_name', 'sku', 'current_stock', 'reorder_point', 'uom'],
                    ],
                    'inventory.transfer.dispatched' => [
                        'label' => 'Stock Transfer Dispatched',
                        'description' => 'Triggered when an inter-warehouse stock transfer is shipped.',
                        'icon' => 'feather-repeat',
                        'default_roles' => ['Store Manager', 'Warehouse Supervisor'],
                        'default_title' => 'Stock Transfer Dispatched: {{transfer_no}}',
                        'default_body' => 'Stock Transfer {{transfer_no}} dispatched from {{from_warehouse}} to {{to_warehouse}}.',
                        'action_route' => 'inventory.transfers.index',
                        'variables' => ['transfer_no', 'from_warehouse', 'to_warehouse', 'items_count'],
                    ],
                    'inventory.transfer.received' => [
                        'label' => 'Stock Transfer Received',
                        'description' => 'Triggered when destination warehouse receives transferred stock.',
                        'icon' => 'feather-check-square',
                        'default_roles' => ['Store Manager'],
                        'default_title' => 'Stock Transfer Received: {{transfer_no}}',
                        'default_body' => 'Stock Transfer {{transfer_no}} has been fully received at {{to_warehouse}} by {{received_by}}.',
                        'action_route' => 'inventory.transfers.index',
                        'variables' => ['transfer_no', 'from_warehouse', 'to_warehouse', 'received_by'],
                    ],
                    'inventory.adjustment.pending' => [
                        'label' => 'Stock Adjustment Approval Pending',
                        'description' => 'Triggered when a physical inventory count adjustment needs approval.',
                        'icon' => 'feather-sliders',
                        'default_roles' => ['Store Manager', 'Admin'],
                        'default_title' => 'Stock Adjustment Approval Required: {{doc_no}}',
                        'default_body' => 'Stock Adjustment {{doc_no}} for warehouse {{warehouse}} submitted by {{created_by}} is pending approval.',
                        'action_route' => 'inventory.adjustments.index',
                        'variables' => ['doc_no', 'warehouse', 'reason', 'created_by'],
                    ],
                    'inventory.batch.expiring' => [
                        'label' => 'Batch Expiring Alert (FEFO)',
                        'description' => 'Triggered when a stock batch is nearing expiration.',
                        'icon' => 'feather-clock',
                        'default_roles' => ['Store Manager', 'Quality Manager'],
                        'default_title' => '⏰ Batch Expiring Soon: {{item_name}} (Batch: {{batch_no}})',
                        'default_body' => 'Batch {{batch_no}} of {{item_name}} (Qty: {{quantity}}) will expire on {{expiry_date}}.',
                        'action_route' => 'inventory.batches.index',
                        'variables' => ['item_name', 'batch_no', 'expiry_date', 'quantity'],
                    ],
                ],
            ],
            'purchase' => [
                'label' => 'Purchase & Procurement',
                'events' => [
                    'purchase.order.created' => [
                        'label' => 'Purchase Order Created',
                        'description' => 'Triggered when a new Purchase Order is created.',
                        'icon' => 'feather-file-plus',
                        'default_roles' => ['Purchase Head', 'Finance Manager'],
                        'default_title' => 'PO Created: {{po_no}} for {{vendor_name}}',
                        'default_body' => 'Purchase Order {{po_no}} for vendor {{vendor_name}} with amount {{amount}} has been created.',
                        'action_route' => 'purchase.orders.index',
                        'variables' => ['po_no', 'vendor_name', 'amount', 'created_by'],
                    ],
                    'purchase.order.approved' => [
                        'label' => 'Purchase Order Approved',
                        'description' => 'Triggered when a PO receives management approval.',
                        'icon' => 'feather-check-circle',
                        'default_roles' => ['Purchase Executive', 'Store Keeper'],
                        'default_title' => 'PO Approved: {{po_no}}',
                        'default_body' => 'PO {{po_no}} for {{vendor_name}} ({{amount}}) has been approved by {{approved_by}}.',
                        'action_route' => 'purchase.orders.index',
                        'variables' => ['po_no', 'vendor_name', 'amount', 'approved_by'],
                    ],
                    'purchase.grn.received' => [
                        'label' => 'Goods Receipt Note (GRN) Completed',
                        'description' => 'Triggered when vendor goods arrive at warehouse and GRN is posted.',
                        'icon' => 'feather-package',
                        'default_roles' => ['Purchase Executive', 'Accountant'],
                        'default_title' => 'GRN Inward Completed: {{grn_no}}',
                        'default_body' => 'Goods Receipt {{grn_no}} for PO {{po_no}} from vendor {{vendor_name}} received at warehouse {{warehouse}}.',
                        'action_route' => 'grns.index',
                        'variables' => ['grn_no', 'vendor_name', 'warehouse', 'po_no'],
                    ],
                    'purchase.bill.created' => [
                        'label' => 'Vendor Bill Logged',
                        'description' => 'Triggered when a vendor bill/invoice is recorded for payment.',
                        'icon' => 'feather-credit-card',
                        'default_roles' => ['Accountant', 'Finance Head'],
                        'default_title' => 'Vendor Bill Logged: {{bill_no}}',
                        'default_body' => 'Vendor Bill {{bill_no}} for {{vendor_name}} ({{amount}}) logged. Payment Due: {{due_date}}.',
                        'action_route' => 'purchase.bills.index',
                        'variables' => ['bill_no', 'vendor_name', 'amount', 'due_date'],
                    ],
                ],
            ],
            'production' => [
                'label' => 'Production & Manufacturing',
                'events' => [
                    'production.order.created' => [
                        'label' => 'Production Order Created',
                        'description' => 'Triggered when a manufacturing production order is released.',
                        'icon' => 'feather-layers',
                        'default_roles' => ['Plant Head', 'Production Supervisor', 'Store Manager'],
                        'default_title' => 'Production Order Released: {{order_no}}',
                        'default_body' => 'Production Order {{order_no}} for {{product_name}} (Qty: {{quantity}}) released. Target: {{target_date}}.',
                        'action_route' => 'production.orders.index',
                        'variables' => ['order_no', 'product_name', 'quantity', 'target_date'],
                    ],
                    'production.job.completed' => [
                        'label' => 'Production Job Completed',
                        'description' => 'Triggered when a job card/work order is finished.',
                        'icon' => 'feather-check',
                        'default_roles' => ['Production Manager', 'Store Manager'],
                        'default_title' => 'Job Card Finished: {{job_no}}',
                        'default_body' => 'Job {{job_no}} for {{product_name}} completed by {{operator_name}}. Output: {{produced_qty}}.',
                        'action_route' => 'production.orders.index',
                        'variables' => ['job_no', 'product_name', 'produced_qty', 'operator_name'],
                    ],
                    'production.qc.failed' => [
                        'label' => 'Quality Inspection Failed (NCR)',
                        'description' => 'Triggered when a QC inspection fails and creates an NCR.',
                        'icon' => 'feather-alert-octagon',
                        'default_roles' => ['Quality Head', 'Plant Manager'],
                        'default_title' => '🔴 QC Inspection Failed: {{inspection_no}}',
                        'default_body' => 'QC Inspection {{inspection_no}} failed for {{item_name}}. Defect: {{defect_type}}, Rejected Qty: {{rejected_qty}}.',
                        'action_route' => 'production.ncrs.index',
                        'variables' => ['inspection_no', 'item_name', 'defect_type', 'rejected_qty'],
                    ],
                ],
            ],
            'document' => [
                'label' => 'Document Management & Compliance',
                'events' => [
                    'hrms.document.uploaded' => [
                        'label' => 'Document Uploaded for Verification',
                        'description' => 'Triggered when an employee uploads a KYC, identity, degree or statutory document.',
                        'icon' => 'feather-file-plus',
                        'default_roles' => ['HR Manager', 'Admin'],
                        'default_title' => '📄 Document Uploaded: {{employee_name}} - {{document_type}}',
                        'default_body' => '{{employee_name}} uploaded a new {{document_type}} under {{category_name}} for verification.',
                        'action_route' => 'hrms.employees.index',
                        'variables' => ['employee_name', 'document_type', 'category_name', 'uploaded_at'],
                    ],
                    'hrms.document.approved' => [
                        'label' => 'Document Verified & Approved',
                        'description' => 'Triggered when HR verifies and approves an uploaded employee document.',
                        'icon' => 'feather-check-circle',
                        'default_roles' => ['HR Manager', 'Employee'],
                        'default_title' => '✅ Document Approved: {{document_type}}',
                        'default_body' => 'Your document {{document_type}} has been verified and approved by {{approved_by}}.',
                        'action_route' => 'hrms.employees.index',
                        'variables' => ['employee_name', 'document_type', 'approved_by', 'date'],
                    ],
                    'hrms.document.rejected' => [
                        'label' => 'Document Rejected (Re-upload Needed)',
                        'description' => 'Triggered when HR rejects a submitted document due to invalid/missing information.',
                        'icon' => 'feather-x-circle',
                        'default_roles' => ['Employee', 'HR Manager'],
                        'default_title' => '⚠️ Document Rejected: {{document_type}}',
                        'default_body' => 'Your document {{document_type}} was rejected by {{rejected_by}}. Reason: {{reason}}. Please re-upload.',
                        'action_route' => 'hrms.employees.index',
                        'variables' => ['employee_name', 'document_type', 'reason', 'rejected_by'],
                    ],
                    'hrms.document.signature_requested' => [
                        'label' => 'E-Signature Required on Document',
                        'description' => 'Triggered when an agreement, policy or letter requires employee digital signature.',
                        'icon' => 'feather-edit-3',
                        'default_roles' => ['Employee', 'HR Manager'],
                        'default_title' => '✍️ Signature Required: {{document_title}}',
                        'default_body' => 'Please review and digitally sign {{document_title}} issued for {{employee_name}} by {{due_date}}.',
                        'action_route' => 'hrms.employees.index',
                        'variables' => ['employee_name', 'document_title', 'due_date'],
                    ],
                    'hrms.document.signed' => [
                        'label' => 'Document E-Signed & Finalized',
                        'description' => 'Triggered when an employee or authority completes their digital signature.',
                        'icon' => 'feather-file-check',
                        'default_roles' => ['HR Manager', 'Admin'],
                        'default_title' => '📝 Document E-Signed: {{document_title}}',
                        'default_body' => '{{employee_name}} has digitally signed and completed the document {{document_title}}.',
                        'action_route' => 'hrms.employees.index',
                        'variables' => ['employee_name', 'document_title', 'signed_at'],
                    ],
                    'hrms.document.expiring_soon' => [
                        'label' => 'Document Expiry Alert (30/15/7 Days)',
                        'description' => 'Triggered when a statutory document (Passport, Visa, License) is nearing expiration.',
                        'icon' => 'feather-clock',
                        'default_roles' => ['HR Manager', 'Employee'],
                        'default_title' => '⏰ Document Expiring Soon: {{document_type}} - {{employee_name}}',
                        'default_body' => '{{document_type}} for {{employee_name}} will expire on {{expiry_date}} (in {{days_left}} days). Please initiate renewal.',
                        'action_route' => 'hrms.employees.index',
                        'variables' => ['employee_name', 'document_type', 'expiry_date', 'days_left'],
                    ],
                    'hrms.document.expired' => [
                        'label' => 'Document Expired (Compliance Warning)',
                        'description' => 'Triggered on document expiry date when mandatory document is expired.',
                        'icon' => 'feather-alert-triangle',
                        'default_roles' => ['HR Manager', 'Admin'],
                        'default_title' => '🔴 Document Expired: {{document_type}} - {{employee_name}}',
                        'default_body' => '{{document_type}} for {{employee_name}} expired on {{expired_on}}. Immediate renewal or re-submission is required.',
                        'action_route' => 'hrms.employees.index',
                        'variables' => ['employee_name', 'document_type', 'expired_on'],
                    ],
                    'hrms.document.letter_issued' => [
                        'label' => 'Official Letter Issued (Offer/Increment/Warning)',
                        'description' => 'Triggered when an official company letter is generated and issued to employee.',
                        'icon' => 'feather-file-text',
                        'default_roles' => ['Employee', 'HR Manager'],
                        'default_title' => '📑 Official Letter Issued: {{letter_type}}',
                        'default_body' => 'A new {{letter_type}} (Ref: {{ref_no}}) has been issued to {{employee_name}}.',
                        'action_route' => 'hrms.employees.index',
                        'variables' => ['employee_name', 'letter_type', 'ref_no', 'issued_date'],
                    ],
                    'hrms.document.exit_cleared' => [
                        'label' => 'Exit Clearance Document Issued',
                        'description' => 'Triggered when relieving letter, experience certificate, or NOC is issued.',
                        'icon' => 'feather-award',
                        'default_roles' => ['Employee', 'HR Manager', 'Accountant'],
                        'default_title' => '🏁 Exit Certificate Issued: {{document_type}} for {{employee_name}}',
                        'default_body' => 'Official {{document_type}} has been generated and released for {{employee_name}} (Relieved on: {{exit_date}}).',
                        'action_route' => 'hrms.employees.index',
                        'variables' => ['employee_name', 'document_type', 'exit_date'],
                    ],
                ],
            ],
            'hrms' => [
                'label' => 'HRMS & Employee Self-Service',
                'events' => [

                    // Leave Management
                    'hrms.leave.applied' => [
                        'label' => 'Leave Application Submitted',
                        'description' => 'Triggered when an employee applies for leave.',
                        'icon' => 'feather-calendar',
                        'default_roles' => ['HR Manager', 'Department Head'],
                        'default_title' => 'Leave Application: {{employee_name}}',
                        'default_body' => '{{employee_name}} applied for {{days}} day(s) {{leave_type}} from {{from_date}} to {{to_date}}.',
                        'action_route' => 'hrms.leaves.index',
                        'variables' => ['employee_name', 'leave_type', 'from_date', 'to_date', 'days'],
                    ],
                    'hrms.leave.approved' => [
                        'label' => 'Leave Application Approved',
                        'description' => 'Triggered when a leave request is approved by manager or HR.',
                        'icon' => 'feather-check-circle',
                        'default_roles' => ['Employee', 'HR Manager'],
                        'default_title' => '✅ Leave Approved: {{leave_type}} ({{days}} days)',
                        'default_body' => 'Your leave application for {{days}} day(s) {{leave_type}} from {{from_date}} to {{to_date}} has been approved by {{approved_by}}.',
                        'action_route' => 'hrms.leaves.index',
                        'variables' => ['employee_name', 'leave_type', 'from_date', 'to_date', 'days', 'approved_by'],
                    ],
                    'hrms.leave.rejected' => [
                        'label' => 'Leave Application Rejected',
                        'description' => 'Triggered when a leave request is declined.',
                        'icon' => 'feather-x-circle',
                        'default_roles' => ['Employee', 'HR Manager'],
                        'default_title' => '❌ Leave Rejected: {{leave_type}}',
                        'default_body' => 'Your leave application from {{from_date}} to {{to_date}} was rejected by {{rejected_by}}. Reason: {{reason}}.',
                        'action_route' => 'hrms.leaves.index',
                        'variables' => ['employee_name', 'leave_type', 'from_date', 'to_date', 'reason', 'rejected_by'],
                    ],

                    // Attendance & Regularization
                    'hrms.attendance.regularization_applied' => [
                        'label' => 'Attendance Regularization Requested',
                        'description' => 'Triggered when an employee requests punch regularization or attendance correction.',
                        'icon' => 'feather-clock',
                        'default_roles' => ['HR Manager', 'Department Head'],
                        'default_title' => 'Attendance Regularization: {{employee_name}}',
                        'default_body' => '{{employee_name}} requested attendance regularization for {{date}} (In: {{check_in}}, Out: {{check_out}}). Reason: {{reason}}.',
                        'action_route' => 'hrms.attendance.index',
                        'variables' => ['employee_name', 'date', 'check_in', 'check_out', 'reason'],
                    ],
                    'hrms.attendance.regularization_approved' => [
                        'label' => 'Attendance Regularization Approved',
                        'description' => 'Triggered when an attendance regularization request is approved.',
                        'icon' => 'feather-check-square',
                        'default_roles' => ['Employee', 'HR Manager'],
                        'default_title' => '✅ Attendance Regularized: {{date}}',
                        'default_body' => 'Your attendance regularization request for {{date}} has been approved by {{approved_by}}.',
                        'action_route' => 'hrms.attendance.index',
                        'variables' => ['employee_name', 'date', 'approved_by'],
                    ],

                    // Work From Home (WFH)
                    'hrms.wfh.applied' => [
                        'label' => 'Work From Home (WFH) Applied',
                        'description' => 'Triggered when an employee submits a Work From Home request.',
                        'icon' => 'feather-home',
                        'default_roles' => ['HR Manager', 'Department Head'],
                        'default_title' => 'WFH Request: {{employee_name}} for {{date}}',
                        'default_body' => '{{employee_name}} requested Work From Home on {{date}}. Reason: {{reason}}.',
                        'action_route' => 'hrms.wfh.index',
                        'variables' => ['employee_name', 'date', 'reason'],
                    ],
                    'hrms.wfh.approved' => [
                        'label' => 'Work From Home (WFH) Approved',
                        'description' => 'Triggered when a WFH request is approved.',
                        'icon' => 'feather-check-circle',
                        'default_roles' => ['Employee', 'HR Manager'],
                        'default_title' => '✅ WFH Request Approved: {{date}}',
                        'default_body' => 'Your WFH request for {{date}} has been approved by {{approved_by}}.',
                        'action_route' => 'hrms.wfh.index',
                        'variables' => ['employee_name', 'date', 'approved_by'],
                    ],

                    // Overtime & Shifts
                    'hrms.overtime.applied' => [
                        'label' => 'Overtime Claim Submitted',
                        'description' => 'Triggered when an employee logs an overtime claim.',
                        'icon' => 'feather-trending-up',
                        'default_roles' => ['HR Manager', 'Department Head', 'Accountant'],
                        'default_title' => 'Overtime Claim: {{employee_name}} ({{hours}} hrs)',
                        'default_body' => '{{employee_name}} logged {{hours}} hours overtime on {{date}}. Reason: {{reason}}.',
                        'action_route' => 'hrms.overtime.index',
                        'variables' => ['employee_name', 'date', 'hours', 'reason'],
                    ],
                    'hrms.overtime.approved' => [
                        'label' => 'Overtime Claim Approved',
                        'description' => 'Triggered when an overtime claim is approved.',
                        'icon' => 'feather-check',
                        'default_roles' => ['Employee', 'HR Manager'],
                        'default_title' => '✅ Overtime Approved: {{hours}} hrs on {{date}}',
                        'default_body' => 'Your overtime claim of {{hours}} hrs on {{date}} has been approved by {{approved_by}}.',
                        'action_route' => 'hrms.overtime.index',
                        'variables' => ['employee_name', 'date', 'hours', 'approved_by'],
                    ],

                    // Travel & Expenses
                    'hrms.expense.submitted' => [
                        'label' => 'Expense Claim Submitted',
                        'description' => 'Triggered when an employee files a travel or reimbursement expense claim.',
                        'icon' => 'feather-navigation',
                        'default_roles' => ['HR Manager', 'Accountant'],
                        'default_title' => 'Expense Claim: {{claim_no}} by {{employee_name}}',
                        'default_body' => 'Expense Claim {{claim_no}} for {{purpose}} (Amount: {{amount}}) submitted by {{employee_name}}.',
                        'action_route' => 'hrms.travel-expense.index',
                        'variables' => ['claim_no', 'employee_name', 'amount', 'purpose'],
                    ],
                    'hrms.expense.approved' => [
                        'label' => 'Expense Claim Approved',
                        'description' => 'Triggered when an expense claim receives management approval.',
                        'icon' => 'feather-check-circle',
                        'default_roles' => ['Accountant', 'Employee'],
                        'default_title' => '✅ Expense Claim Approved: {{claim_no}}',
                        'default_body' => 'Expense Claim {{claim_no}} of {{amount}} for {{employee_name}} has been approved by {{approved_by}}.',
                        'action_route' => 'hrms.travel-expense.index',
                        'variables' => ['claim_no', 'employee_name', 'amount', 'approved_by'],
                    ],
                    'hrms.expense.settled' => [
                        'label' => 'Expense Claim Reimbursed / Settled',
                        'description' => 'Triggered when finance processes and reimburses the expense payment.',
                        'icon' => 'feather-dollar-sign',
                        'default_roles' => ['Employee', 'HR Manager'],
                        'default_title' => '💰 Expense Reimbursed: {{claim_no}}',
                        'default_body' => 'Payment of {{amount}} for expense claim {{claim_no}} has been processed via {{payment_mode}}.',
                        'action_route' => 'hrms.travel-expense.index',
                        'variables' => ['claim_no', 'employee_name', 'amount', 'payment_mode'],
                    ],

                    // Payroll & Payslips
                    'hrms.payroll.processed' => [
                        'label' => 'Monthly Payroll Processed',
                        'description' => 'Triggered when the monthly salary computation batch is closed and posted.',
                        'icon' => 'feather-credit-card',
                        'default_roles' => ['HR Manager', 'Finance Head', 'Admin'],
                        'default_title' => '💳 Payroll Processed: {{month_year}}',
                        'default_body' => 'Monthly payroll for {{month_year}} has been computed for {{total_employees}} employees. Total Gross: {{gross_amount}}.',
                        'action_route' => 'hrms.payroll.index',
                        'variables' => ['month_year', 'total_employees', 'gross_amount'],
                    ],
                    'hrms.payslip.published' => [
                        'label' => 'Payslip Published for Employee',
                        'description' => 'Triggered when individual salary payslips are published and accessible.',
                        'icon' => 'feather-file-text',
                        'default_roles' => ['Employee'],
                        'default_title' => '📄 Payslip Available: {{month_year}}',
                        'default_body' => 'Your salary payslip for {{month_year}} (Net Pay: {{net_salary}}) is now available for download.',
                        'action_route' => 'hrms.payslips.index',
                        'variables' => ['employee_name', 'month_year', 'net_salary'],
                    ],

                    // Broadcasts
                    'hrms.broadcast.published' => [
                        'label' => 'Company Broadcast / Notice Published',
                        'description' => 'Triggered when HR or Admin publishes an official company announcement.',
                        'icon' => 'feather-radio',
                        'default_roles' => ['Employee', 'HR Manager'],
                        'default_title' => '📢 Announcement: {{title}}',
                        'default_body' => '{{title}} (Priority: {{priority}}) has been published by {{published_by}}.',
                        'action_route' => 'hrms.broadcasts.index',
                        'variables' => ['broadcast_no', 'title', 'priority', 'published_by'],
                    ],

                    // Helpdesk & Grievance Tickets
                    'hrms.ticket.created' => [
                        'label' => 'HR / IT Helpdesk Ticket Raised',
                        'description' => 'Triggered when an employee files a support or grievance ticket.',
                        'icon' => 'feather-help-circle',
                        'default_roles' => ['HR Manager', 'Admin'],
                        'default_title' => '🎫 New Ticket #{{ticket_no}}: {{subject}}',
                        'default_body' => '{{employee_name}} raised ticket #{{ticket_no}} (Category: {{category}}, Priority: {{priority}}).',
                        'action_route' => 'hrms.tickets.index',
                        'variables' => ['ticket_no', 'subject', 'category', 'priority', 'employee_name'],
                    ],
                    'hrms.ticket.resolved' => [
                        'label' => 'Helpdesk Ticket Resolved',
                        'description' => 'Triggered when a support ticket is marked as resolved/closed.',
                        'icon' => 'feather-check-circle',
                        'default_roles' => ['Employee', 'HR Manager'],
                        'default_title' => '✅ Ticket #{{ticket_no}} Resolved',
                        'default_body' => 'Your ticket #{{ticket_no}} ({{subject}}) has been resolved by {{resolved_by}}.',
                        'action_route' => 'hrms.tickets.index',
                        'variables' => ['ticket_no', 'subject', 'resolved_by'],
                    ],

                    // Employee Lifecycle
                    'hrms.employee.onboarded' => [
                        'label' => 'New Employee Onboarded',
                        'description' => 'Triggered when a new employee record is created/onboarded.',
                        'icon' => 'feather-user-check',
                        'default_roles' => ['HR Manager', 'Department Head', 'Admin'],
                        'default_title' => '🎉 Welcome {{employee_name}} to {{department}}',
                        'default_body' => '{{employee_name}} has joined as {{designation}} in {{department}} (Employee ID: {{employee_code}}).',
                        'action_route' => 'hrms.employees.index',
                        'variables' => ['employee_name', 'employee_code', 'designation', 'department', 'joining_date'],
                    ],
                ],
            ],
        ];
    }

    /**
     * Flat map of event_key => details
     */
    public static function getEventDetails(string $eventKey): ?array
    {
        foreach (self::getEvents() as $moduleKey => $module) {
            if (isset($module['events'][$eventKey])) {
                $details = $module['events'][$eventKey];
                $details['module'] = $moduleKey;
                return $details;
            }
        }
        return null;
    }
}
